[package]
name = "atkins_sieve_serial"
version = "0.1.0"
authors = ["Jason Reilly <jdr0887@gmail.com>"]

[dependencies]

rand = "0.3.0"
log = { version = "^0.4.1", features = ["std"] }
simple_logger = "0.5.0"